# This is a basic workflow to help you get started with Actions
name: part-flow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo hello from part

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo work flow flow
          echo showtime showtime
          echo env ${{env.label}}
