name: part-flow
on:
  workflow_call:
    secrets:
      label:
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo hello from part

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo work flow flow
          echo showtime showtime
          echo env ${{secrets.label}}
